<acceptance-test-run title="Logging on with an incorrect password" name="Logging on with an incorrect password" steps="4" successful="3" failures="1" skipped="0" ignored="0" pending="0" result="FAILURE" duration="81" timestamp="2014-06-29T13:04:54.548+10:00">
  <user-story id="logging_on" name="Logging on" path="stories/authentication/logging_on.story"/>
  <issues>
    <issue>FH-7</issue>
  </issues>
  <versions>
    <version>Release 1.0</version>
    <version>Iteration 1.1</version>
  </versions>
  <tags>
    <tag name="Authentication" type="Epic"/>
    <tag name="Iteration 1.1" type="Version"/>
    <tag name="Release 1.0" type="Version"/>
    <tag name="ui" type="component"/>
    <tag name="Logging on" type="story"/>
  </tags>
  <test-group name="Registering for the site" result="SUCCESS">
    <test-step result="SUCCESS" duration="2">
      <description>Given {Joe} is a Frequent Flyer member</description>
    </test-step>
    <test-step result="SUCCESS" duration="3">
      <description>And {Joe} has registered online with a password of &apos;secret&apos;</description>
    </test-step>
  </test-group>
  <test-step result="SUCCESS" duration="3">
    <description>When {Joe} logs on with password &apos;wrong&apos;</description>
  </test-step>
  <test-step result="FAILURE" duration="20">
    <description>Then he should be informed that his password was incorrect</description>
    <error>expected:&lt;&apos;[expected] message&apos;&gt; but was:&lt;&apos;[wrong] message&apos;&gt;</error>
    <exception>net.thucydides.core.steps.StepFailureException: expected:&lt;&apos;[expected] message&apos;&gt; but was:&lt;&apos;[wrong] message&apos;&gt;
	at net.thucydides.core.steps.BaseStepListener.recordFailureDetailsInFailingTestStep(BaseStepListener.java:493)
	at net.thucydides.core.steps.BaseStepListener.stepFailed(BaseStepListener.java:481)
	at net.thucydides.core.steps.StepEventBus.stepFailed(StepEventBus.java:309)
	at net.thucydides.jbehave.ThucydidesReporter.failed(ThucydidesReporter.java:554)
	at org.jbehave.core.reporters.DelegatingStoryReporter.failed(DelegatingStoryReporter.java:103)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.failed(ConcurrentStoryReporter.java:272)
	at org.jbehave.core.steps.AbstractStepResult$Failed.describeTo(AbstractStepResult.java:57)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:536)
	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:515)
	at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:479)
	at org.jbehave.core.embedder.StoryRunner.runStepsWithLifecycle(StoryRunner.java:445)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:305)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:235)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:207)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.junit.ComparisonFailure: expected:&lt;&apos;[expected] message&apos;&gt; but was:&lt;&apos;[wrong] message&apos;&gt;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.fest.assertions.ConstructorInvoker.newInstance(ConstructorInvoker.java:36)
	at org.fest.assertions.ComparisonFailureFactory.newComparisonFailure(ComparisonFailureFactory.java:60)
	at org.fest.assertions.ComparisonFailureFactory.comparisonFailure(ComparisonFailureFactory.java:46)
	at org.fest.assertions.Fail.comparisonFailed(Fail.java:83)
	at org.fest.assertions.Fail.failIfNotEqual(Fail.java:71)
	at org.fest.assertions.GenericAssert.isEqualTo(GenericAssert.java:217)
	at com.bddinaction.flyinghigh.jbehave.steps.LoginSteps.he_should_be_informed_that_his_password_was_incorrect(LoginSteps.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jbehave.core.steps.StepCreator$ParameterisedStep.perform(StepCreator.java:569)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:535)
	... 12 more
</exception>
  </test-step>
</acceptance-test-run>